import { User, UserRole } from '@prisma/client';

export const userSeed: User[] = [
  {
    id: '1',
    firstName: 'Admin',
    lastName: 'Tuguiapro',
    email: 'admin@tuguiapro.com',
    phone: '+56912345678',
    passwordHash: 'password',
    role: UserRole.provider,
    avatarUrl: undefined,
    lat: undefined,
    lng: undefined,
    city: 'Colima',
    state: 'Colima',
    address: 'Dirección de ejemplo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    firstName: 'Cliente',
    lastName: 'Tuguiapro',
    email: 'cliente@tuguiapro.com',
    phone: '+56912345678',
    passwordHash: 'password',
    role: UserRole.client,
    avatarUrl: undefined,
    lat: undefined,
    lng: undefined,
    city: 'Colima',
    state: 'Colima',
    address: 'Dirección de ejemplo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
